
image:
  file: .gitpod.Dockerfile
tasks:
  - name: initial
    init:
      go install github.com/go-task/task/v3/cmd/task@latest &&
      dart --disable-analytics &&
      dart pub get

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
