
image:
  file: .gitpod.Dockerfile
tasks:
  - name: initial
    init:
      go install github.com/go-task/task/v3/cmd/task@latest

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
