name: try_dart
description: This is my TUTORIAL project for dart.
version: 1.0.0
homepage: https://github.com/devlights/try-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dependencies: 
  pedantic: ^1.11.1
