# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - dart --version
    silent: false
  init:
    cmds:
      - dart create . --force
      - git restore README.md
      - git restore .gitignore
  clean:
    cmds:
      - rm -rf bin/ doc/ lib/ test/ .dart_tool/
      - rm -f analysis_options.yaml pubspec.*
  run:
    cmds:
      - dart run
