# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Show dart version
    cmds:
      - dart --version
    silent: false
  run:
    desc: Run
    deps: [ build ]
    cmds:
      - bin/try_dart.exe
  vet:
    desc: Run dart analyze
    cmds:
      - dart analyze
  fmt:
    desc: Run dart format
    cmds:
      - dart format .
  build:
    desc: Run dart compile
    cmds:
      - dart compile exe bin/try_dart.dart
